language: bash

sudo: required

os:
  - linux
  - osx

addons:
  homebrew:
    packages:
      - bazel

before_install:
  # Install Bazel on Linux.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install curl; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install bazel; fi
  # Install Bazel on macOS.
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask install homebrew/cask-versions/adoptopenjdk8; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install bazel; fi

script:
  - tools/run_tests.sh
