language: bash

sudo: required

os:
  - linux
  - osx

before_install:
  - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - sudo apt install curl
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt update
  - sudo apt install bazel

script:
  - tools/run_tests.sh
