language: bash

sudo: required

os:
  - linux
  - osx

dist: focal
osx_image: xcode12.2

addons:
  apt:
    sources:
      - sourceline: "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8"
        key_url: "https://bazel.build/bazel-release.pub.gpg"
    packages:
      - bazel
  homebrew:
    update: true
    taps:
      - bazelbuild/tap
    packages:
      - bazelbuild/tap/bazel

script:
  - tools/run_tests.sh
