language: bash

sudo: required

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/1.0.1/bazel_1.0.1-linux-x86_64.deb
  - sha256sum -c tools/bazel_1.0.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_1.0.1-linux-x86_64.deb

script:
  - tools/run_tests.sh
