package(default_visibility = ["//visibility:public"])

config_setting(
    name = "darwin",
    values = {"host_cpu": "darwin"},
)

config_setting(
    name = "darwin_arm64",
    values = {"host_cpu": "darwin_arm64"},
)

config_setting(
    name = "k8",
    values = {"host_cpu": "k8"},
)

config_setting(
    name = "coverage_config",
    values = {
        "collect_code_coverage": "true",
    },
)
