load("//dart/build_rules:core.bzl", "dart_library")
load("//dart/build_rules:vm.bzl", "dart_vm_test")

package(default_visibility = ["//visibility:public"])

dart_library(
    name = "greet_lib",
    srcs = ["lib/greet.dart"],
)
