name: Build

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install bazel
        run: tools/install_deps.sh

      - name: Run tests
        run: tools/run_tests.sh
