name: Build

on:
  # Run workflow on any pull request.
  pull_request:

  # Run workflow on pushes to the master branch.
  push:
    branches: [master]

jobs:
  buildifier:
    name: Buildifier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Buildifier checks
        uses: thompsonja/bazel-buildifier@v0.4.0
        with:
          warnings: all

  run-tests:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install bazel
        run: tools/install_deps.sh

      - name: Run tests
        run: tools/run_tests.sh
