load("//dart/build_rules:proto.bzl", "dart_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "person_proto",
    srcs = [
        "person.proto",
        "device.proto",
    ],
)
