load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "person_proto",
    srcs = [
        "person.proto",
        "device.proto",
    ],
)
